spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/ecom_demo
spring.datasource.username=riyaz
spring.datasource.password=Password@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

product.service.selected-service=storageProductService